# Generated by Django 2.1.5 on 2020-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('contribution', models.CharField(max_length=1000)),
            ],
        ),
    ]
