# Generated by Django 2.1.5 on 2020-04-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
